### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by GoChartingAdmin** [rongierlach/react-trading-ui#7]
I would like to thank you for the library.  We refactored the library to use it in our production platform and it works like a charm.

Appreciate the good work!!!!

Please close the issue whenever you feel like

**Comment by youfoundron** [comment]
Love to hear that! Best of luck with your platform.

**Comment by GoChartingAdmin** [comment]
In case you wanted to see it in action

**[GoCharting](https://gocharting.com/terminal/IN/CRYPTO/BTC%7CUSDT/Binance)**

![image](https://user-images.githubusercontent.com/20324844/42413904-90c99466-822a-11e8-82a3-b737e9d87ae0.png)
